Amore.PizzaPoll/Models/GoodieFormModel.cs
using System.Collections.Generic;

namespace Amore.PizzaPoll.Models
{
    public class GoodieFormModel
    {
        public string PizzaId { get; set; }
        public Dictionary<string, bool> SelectedGoodies { get; } = new Dictionary<string, bool>() // goodieId -> isDefault, isSelected
        {
            {"anchovies", false},
            {"artichokes", false},
            {"aubergine", false},
            {"basil", false},
            {"blackolives", false},
            {"buffalomozzarella", false},
            {"capers", false},
            {"cocktailtomatoes", false},
            {"corn", false},
            {"fullgrain", false},
            {"garlic", false},
            {"ham", false},
            {"mozzarella", false},
            {"mushrooms", false},
            {"oliveoil", false},
            {"onion", false},
            {"oregano", false},
            {"parmesan", false},
            {"pepper", false},
            {"rawham", false},
            {"ricotta", false},
            {"rucola", false},
            {"spicysalami", false},
            {"tomatosauce", false},
            {"tuna", false},
            {"zucchini", false},
        };
    }
}

Amore.PizzaPoll/Pages/Admin/Index.cshtml.cs
using System.Threading.Tasks;
using Amore.Data.Website.Context;
using Amore.Domain.Data.Model;
using Amore.Domain.Data.Provider;
using Amore.Domain.Order;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Amore.PizzaPoll.Pages.Admin
{
    public class AdminIndexModel : PageModel
    {
        private readonly IAmoreOrderService _orderService;
        private readonly ISessionProvider _sessionProvider;

        public AdminIndexModel(IAmoreOrderService orderService, ISessionProvider sessionProvider, IAmoreCheckoutDataProvider checkoutDataProvider)
        {
            _orderService = orderService;
            _sessionProvider = sessionProvider;
            CheckoutDataProvider = checkoutDataProvider;
        }

        public bool HasCurrentSession { get; private set; }
        public string CurrentSessionId { get; private set; }
        public CompleteOrderInfo OrderInfo { get; private set; }
        public IAmoreCheckoutDataProvider CheckoutDataProvider { get; }

        public async void OnGet()
        {
            HasCurrentSession = _sessionProvider.HasCurrentSession();
            CurrentSessionId = _sessionProvider.GetCurrentSession();
            OrderInfo = await _orderService.GetOrderInfo();
        }

        public async Task<IActionResult> OnGetOpenSession()
        {
            if (!_sessionProvider.HasCurrentSession())
            {
                await _orderService.OpenSession();
            }
            
            return RedirectToPage("Index");
        }

        public IActionResult OnGetCloseSession()
        {
            if (_sessionProvider.HasCurrentSession())
            {
                _orderService.Checkout();
                _sessionProvider.ReleaseCurrentSession();
            }

            return RedirectToPage("Index");
        }
    }
}

Amore.PizzaPoll/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace App.Pages
{
    public class Error : PageModel
    {
        public void OnGet()
        {
            
        }
    }
}

Amore.PizzaPoll/Pages/Index.cshtml.cs
using System.Collections.Generic;
using Amore.Domain.Data.Dao;
using Amore.Domain.Data.Model;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Amore.PizzaPoll.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IPizzaDao _pizzaDao;

        public IndexModel(IPizzaDao pizzaDao)
        {
            _pizzaDao = pizzaDao;
        }

        public IEnumerable<Pizza> Pizzas { get; private set; }
        
        public async void OnGet()
        {
            Pizzas = await _pizzaDao.GetAll();
        }
    }
}

Amore.PizzaPoll/Pages/Order/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Amore.PizzaPoll.Pages.Order
{
    public class Error : PageModel
    {
        public string ErrorMessage { get; private set; }
        
        public void OnGet(string message)
        {
            ErrorMessage = message;
        }
    }
}

Amore.PizzaPoll/Pages/Order/Index.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Amore.Data.Website.Context;
using Amore.Domain.Data.Dao;
using Amore.Domain.Data.Model;
using Amore.Domain.Data.Provider;
using Amore.Domain.Order;
using Amore.PizzaPoll.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Amore.PizzaPoll.Pages.Order
{
    public class IndexOrderModel : PageModel
    {
        private readonly IPizzaDao _pizzaDao;
        private readonly IAmoreCheckoutDataProvider _checkoutDataProvider;
        private readonly IGoodieDao _goodieDao;
        private readonly IAmoreOrderService _amoreOrderService;
        private readonly ISessionProvider _sessionProvider;

        public IndexOrderModel(IPizzaDao pizzaDao, IAmoreCheckoutDataProvider checkoutDataProvider, IGoodieDao goodieDao, IAmoreOrderService amoreOrderService, ISessionProvider sessionProvider)
        {
            _pizzaDao = pizzaDao;
            _checkoutDataProvider = checkoutDataProvider;
            _goodieDao = goodieDao;
            _amoreOrderService = amoreOrderService;
            _sessionProvider = sessionProvider;
        }

        public Pizza Pizza { get; private set; }
        public IEnumerable<Goodie> AdditionalGoodies { get; private set; }
        [BindProperty]
        public GoodieFormModel FormModel { get; set; }

        public async Task<IActionResult> OnGet(string pizzaId)
        {
            if (!_sessionProvider.HasCurrentSession())
            {
                return RedirectToPage("../Index");
            }
            
            Pizza = await _pizzaDao.GetById(pizzaId);

            if (Pizza == null)
            {
                return NotFound();
            }

            FormModel = new GoodieFormModel {PizzaId = pizzaId};

            (Pizza.DefaultGoodiesIds as List<string>)?.ForEach(goodieId => FormModel.SelectedGoodies[goodieId] = true);

            AdditionalGoodies = await _goodieDao.GetAllWithId(Pizza.AdditionalGoodiesIds.ToArray());

            return Page();

        }

        public async Task<IActionResult> OnPost()
        {
            var pizza = await _pizzaDao.GetById(FormModel.PizzaId);

            if (pizza == null)
            {
                return NotFound();
            }
            
            var selectedGoodieIds = FormModel.SelectedGoodies
                .Where(pair => pair.Value)
                .Select(pair => pair.Key).ToList();
            
            if (selectedGoodieIds.Intersect(pizza.DefaultGoodiesIds).Count() < 2 || selectedGoodieIds.Except(pizza.DefaultGoodiesIds).Count() > 2)
            {
                return RedirectToPage("Error", new {message = "Du hast eine ungültige Anzahl an Goodies ausgewählt"});
            }

            var goodies = await _goodieDao.GetAllWithId(selectedGoodieIds.ToArray());

            _amoreOrderService.PutOrder(pizza, goodies);

            return RedirectToPage("Success");
        }
    }
}

Amore.PizzaPoll/Pages/Order/Success.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Amore.PizzaPoll.Pages.Order
{
    public class Success : PageModel
    {
        public void OnGet()
        {
            
        }
    }
}

Amore.PizzaPoll/Pages/Admin/Index.cshtml
@page "{handler?}"
@model Amore.PizzaPoll.Pages.Admin.AdminIndexModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = "Shared/_Layout";
}

<h1 class="mt-3 mb-4">
    Admin page
</h1>

<div>
    @if (Model.HasCurrentSession)
    {
        <div>
            <h3>
                Userdata
            </h3>
            <div class="shadow p-2 mb-5 bg-amore-secondary rounded">
                <p>
                    <strong>Firstname</strong>: @Model.CheckoutDataProvider.FirstName
                </p>
                <p>
                    <strong>Lastname</strong>: @Model.CheckoutDataProvider.LastName
                </p>
                <p>
                    <strong>Address</strong>: @Model.CheckoutDataProvider.Address
                </p>
                <p>
                    <strong>Housenumber</strong>: @Model.CheckoutDataProvider.HouseNumber
                </p>
                <p>
                    <strong>Floor</strong>: @Model.CheckoutDataProvider.Floor
                </p>
                <p>
                    <strong>Door</strong>: @Model.CheckoutDataProvider.Door
                </p>
                <p>
                    <strong>City</strong>: @Model.CheckoutDataProvider.City
                </p>
                <p>
                    <strong>Zip</strong>: @Model.CheckoutDataProvider.Zip
                </p>
                <p>
                    <strong>Specialinstructions</strong>: @Model.CheckoutDataProvider.SpecialInstructions
                </p>
            </div>

            <h3>
                Current order
            </h3>
            <div class="shadow p-2 mb-5 bg-amore-secondary rounded">
                <h5>
                    Subtotal: € <strong>@Model.OrderInfo.SubTotal</strong> ,-
                </h5>
                <p>
                    Amore Order Session ID: <strong>@Model.CurrentSessionId</strong>
                </p>

                <p class="text-red">
                    <a asp-page-handler="closesession" class="btn bg-amore-primary text-white mb-1">Checkout</a><br>
                    There is no a guarantee for the correctness and completeness of this order. Prices may vary or the order process might fail completely.
                </p>
            </div>

            <div>
                <h3>
                    Cart
                </h3>
                <table class="table">
                    <thead class="bg-amore-secondary">
                    <tr>
                        <th scope="col">Product</th>
                        <th scope="col">Price*</th>
                        <th scope="col">Extras</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var item in Model.OrderInfo.OrderItemInfo)
                    {
                        <tr>
                            <th scope="row">@item.Item1</th>
                            <td>@item.Item3</td>
                            <td>@item.Item2</td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        </div>
    }
    else
    {
        <h3>
            Currently no order
        </h3>

        <p class="text-red">
            <a asp-page-handler="opensession">Open order</a>
        </p>
    }
</div>

Amore.PizzaPoll/Pages/Index.cshtml
@page
@model Amore.PizzaPoll.Pages.IndexModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = "_Layout";
}

<header class="text-center">
    <img src="img/header-pizza.jpg" class="img-fluid p-2 w-100" alt="pizza-header">
</header>

<section class="pizza-list">
    
    @foreach (var pizza in Model.Pizzas)
    {
        <div class="media pizza-item shadow rounded bg-amore-secondary">
            
            <img src="@pizza.ProductImagePath" class="mr-3 d-none d-md-block" alt="pizza-image">
            
            <div class="media-body h-100 pt-2">
                
                <div class="h-100 w-75 d-inline-block align-middle">
                    <h5 class="mt-0 amore-font">@pizza.Name</h5>
                    @pizza.Description
                </div>
                
                <div class="h-100 w-24 d-inline-block text-center">
                    <a asp-page="/Order/Index" asp-route-pizzaId="@pizza.Id" class="btn bg-amore-primary text-white" role="button">Bestellen</a>
                </div>
                
            </div>
        </div>
    }
    
</section>

Amore.PizzaPoll/Pages/Order/Index.cshtml
@page "{pizzaId}"
@model Amore.PizzaPoll.Pages.Order.IndexOrderModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = "Shared/_Layout";
}

<div class="media pizza-item shadow rounded bg-amore-secondary mt-2 sticky-top">
    <img src="@($"/{Model.Pizza.ProductImagePath}")" class="mr-3 d-none d-md-block" alt="pizza-image">
    <div class="media-body h-100 pt-2">
        <div class="h-100 w-100">
            <h5 class="mt-0">Deine Pizza</h5>
            <h4 class="amore-font">@Model.Pizza.Name</h4>
        </div>
    </div>
</div>

<section class="pizza-order">

    <div class="d-block mt-4">
        <h4>Noch ein paar Goodies gefällig?</h4>
        <p>
            Du kannst höchstens <strong>zwei</strong> zusätzliche Goodies wählen, und höchstens <strong>zwei</strong> Standardgoodies abwählen.
        </p>

        <form class="pb-4" method="post">

            <div class="pl-3 mb-3">
                <input asp-for="FormModel.PizzaId" value="@Model.Pizza.Id" hidden/>
                @foreach (var goodie in Model.AdditionalGoodies)
                {
                    <div class="form-check">
                        <input asp-for="@Model.FormModel.SelectedGoodies[goodie.Id]"/>
                        <label asp-for="@Model.FormModel.SelectedGoodies[goodie.Id]">@goodie.Name</label>
                    </div>
                }
            </div>

            <button type="submit" class="btn bg-amore-primary w-100 text-white">
                <svg class="bi bi-check" width="24" height="24" viewBox="0 0 20 20" fill="currentColor"
                     xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                          d="M15.854 5.646a.5.5 0 010 .708l-7 7a.5.5 0 01-.708 0l-3.5-3.5a.5.5 0 11.708-.708L8.5 12.293l6.646-6.647a.5.5 0 01.708 0z"
                          clip-rule="evenodd">
                    </path>
                </svg>
                Bestellen
            </button>
        </form>
    </div>
</section>

Amore.PizzaPoll/Pages/Order/Success.cshtml
@page
@model Amore.PizzaPoll.Pages.Order.Success

@{
    Layout = "Shared/_Layout";
}

<h1>
    Deine Bestellung war erfolgreich. Guten Appetit!
</h1>

Amore.PizzaPoll/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Amore's Pizza Poll</title>
    <link rel="icon" href="/img/icon.svg"/>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="/css/site.css">
</head>
<body>

<nav class="navbar navbar-dark bg-amore-primary">
    <a href="/" class="navbar-brand mb-0 h1 amore-font">
        Amore's Pizza Poll
    </a>
</nav>

<main>
    @RenderBody()
</main>

</body>

@RenderSection("Scripts", required: false)

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</html>